### ISSUE TITLE
stateless is not atomic

### ISSUE THREAD

**Issue by hmoffatt** [ansibleguy/linux_ufw#1]
Do you think it is worth documenting that the stateless mode is not atomic? There's a window where you have no firewall at all while the rules are replaced. It's a pity that ufw doesn't have better support for this.

**Comment by ansibleguy** [comment]
I actually also started to dislike the way UFW behaves.
In my eyes it is not a tool that is designed to be automated.

I would actually recommend using NFTables if that is an issue: https://github.com/ansibleguy/infra_nftables
There the config is written as config-file and one does not have to deal with the added complexity of single-rule changes.

**Comment by hmoffatt** [comment]
Thanks, I have been thinking that I would prefer a firewall where all the rules can simply be declared in one place rather than having its own state with add/remove commands. I think firewalld is also like ufw in this way.

**Comment by ansibleguy** [comment]
Yes - firewalld and ufw are similar in this aspect.
IMHO they make sense for simple rulesets and if managing rules manually over cli.
But I don't think that these 'cli tools' are really a good solution for more complex setups.

One thing to keep in mind: firewalld and ufw acutally set some defaults that you will have to define manually when using raw IPTables/NFTables.
But I also have some nice config-examples for NFTables in the other repo: [Examples](https://github.com/ansibleguy/infra_nftables/blob/latest/docs/UseCaseExamples.md)
